### ISSUE TITLE
The problem of $COMPOSER_PREFER_LOWEST variable

### ISSUE THREAD

**Issue by peter279k** [mintware-de/streams#1]
As title, it looks like the `composer update` command option relies on this `$COMPOSER_PREFER_LOWEST ` environment variable.

Actually, we cannot find where this environment variable is set currently.

To resolve this issue, we should do following tips:

- Define a `COMPOSER_PREFER_LOWEST` environment vairable and set `true` to do the `composer update --prefer-source` command.
- Define a `COMPOSER_PREFER_LOWEST` environment vairable and set `false` to do the `composer update --prefer-source --prefer-lowest --prefer-stable` command.

Once this issue is accepted, I'm happy to work on this.

**Comment by peter279k** [comment]
BTW, here is a [tutorial](https://github.com/helios-ag/FMSummernoteBundle/blob/master/.travis.yml#L11) about setting environment variables on Travis CI build.

**Comment by devtronic** [comment]
Thanks for opening the issue. I've assigned it to you.

I think the best way is to create a [matrix](https://docs.travis-ci.com/user/customizing-the-build/#build-matrix) entry in the `.travis.yml` to test both cases. 

For example:
```yaml
matrix:
  include:
  - name: "Prefer Source"
    env: COMPOSER_PREFER_LOWEST=false
  - name: "Prefer Lowest"
    env: COMPOSER_PREFER_LOWEST=true
```
